version: '3.8'

services:
  uppies:
    build: .
    ports:
      - '127.0.0.1:3000:3000' # Only bind to localhost, not public
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_PUBLIC_APPWRITE_ENDPOINT
      - VITE_PUBLIC_APPWRITE_PROJECT_ID
      - APPWRITE_API_SECRET
