# DigitalOcean App Platform specification
# Use this for deploying via DigitalOcean App Platform

name: uppies
services:
- name: web
  source_dir: /
  github:
    repo: sxxxnx/uppies
    branch: main
  build_command: bun install && bun run build
  run_command: bun run start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: APPWRITE_PROJECT_ID
    value: ${APPWRITE_PROJECT_ID}
  - key: APPWRITE_ENDPOINT
    value: ${APPWRITE_ENDPOINT}
  - key: APPWRITE_API_KEY
    value: ${APPWRITE_API_KEY}
  - key: APPWRITE_DATABASE_ID
    value: ${APPWRITE_DATABASE_ID}
  - key: APPWRITE_COLLECTION_ID
    value: ${APPWRITE_COLLECTION_ID}
  - key: APPWRITE_STORAGE_ID
    value: ${APPWRITE_STORAGE_ID}
  - key: PORT
    value: "8080"
